-- MySQL Script generated by MySQL Workbench
-- Fri Nov 15 21:54:17 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  `Telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veiculo` (
  `idVeiculo` INT NOT NULL,
  `Placa` VARCHAR(45) NULL,
  `Modelo` VARCHAR(45) NULL,
  `Marca` VARCHAR(45) NULL,
  `ano` DATE NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idVeiculo`, `Cliente_idCliente`),
  INDEX `fk_Veiculo_Cliente_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mecanico` (
  `idMecanico` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Especialidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idMecanico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem De Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ordem De Serviço` (
  `idOrdem De Serviço` INT NOT NULL,
  `data-emissao` DATE NULL,
  `Valor` VARCHAR(45) NULL,
  `Status` VARCHAR(45) NULL,
  `Data Conclusao` DATE NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Veiculo_idVeiculo` INT NOT NULL,
  PRIMARY KEY (`idOrdem De Serviço`, `Cliente_idCliente`, `Veiculo_idVeiculo`),
  INDEX `fk_Ordem De Serviço_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Ordem De Serviço_Veiculo1_idx` (`Veiculo_idVeiculo` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem De Serviço_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem De Serviço_Veiculo1`
    FOREIGN KEY (`Veiculo_idVeiculo`)
    REFERENCES `mydb`.`Veiculo` (`idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Serviço` (
  `idServiço` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `valor mao de obra` DECIMAL NULL,
  PRIMARY KEY (`idServiço`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peça`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peça` (
  `idPeça` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `valor-unitario` DECIMAL NULL,
  PRIMARY KEY (`idPeça`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipe` (
  `idEquipe` INT NOT NULL,
  `Mecanicos` VARCHAR(45) NULL,
  `Ordem De Serviço_Veiculo_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idEquipe`, `Ordem De Serviço_Veiculo_Cliente_idCliente`))
ENGINE = InnoDB
COMMENT = 'E	QUIPE';


-- -----------------------------------------------------
-- Table `mydb`.`Serviço_has_Ordem De Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Serviço_has_Ordem De Serviço` (
  `Serviço_idServiço` INT NOT NULL,
  `Ordem De Serviço_idOrdem De Serviço` INT NOT NULL,
  `Ordem De Serviço_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`Serviço_idServiço`, `Ordem De Serviço_idOrdem De Serviço`, `Ordem De Serviço_Cliente_idCliente`),
  INDEX `fk_Serviço_has_Ordem De Serviço_Ordem De Serviço1_idx` (`Ordem De Serviço_idOrdem De Serviço` ASC, `Ordem De Serviço_Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Serviço_has_Ordem De Serviço_Serviço1_idx` (`Serviço_idServiço` ASC) VISIBLE,
  CONSTRAINT `fk_Serviço_has_Ordem De Serviço_Serviço1`
    FOREIGN KEY (`Serviço_idServiço`)
    REFERENCES `mydb`.`Serviço` (`idServiço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Serviço_has_Ordem De Serviço_Ordem De Serviço1`
    FOREIGN KEY (`Ordem De Serviço_idOrdem De Serviço` , `Ordem De Serviço_Cliente_idCliente`)
    REFERENCES `mydb`.`Ordem De Serviço` (`idOrdem De Serviço` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecanico_has_Ordem De Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mecanico_has_Ordem De Serviço` (
  `Mecanico_idMecanico` INT NOT NULL,
  `Ordem De Serviço_idOrdem De Serviço` INT NOT NULL,
  PRIMARY KEY (`Mecanico_idMecanico`, `Ordem De Serviço_idOrdem De Serviço`),
  INDEX `fk_Mecanico_has_Ordem De Serviço_Ordem De Serviço1_idx` (`Ordem De Serviço_idOrdem De Serviço` ASC) VISIBLE,
  INDEX `fk_Mecanico_has_Ordem De Serviço_Mecanico1_idx` (`Mecanico_idMecanico` ASC) VISIBLE,
  CONSTRAINT `fk_Mecanico_has_Ordem De Serviço_Mecanico1`
    FOREIGN KEY (`Mecanico_idMecanico`)
    REFERENCES `mydb`.`Mecanico` (`idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mecanico_has_Ordem De Serviço_Ordem De Serviço1`
    FOREIGN KEY (`Ordem De Serviço_idOrdem De Serviço`)
    REFERENCES `mydb`.`Ordem De Serviço` (`idOrdem De Serviço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`itens da os`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`itens da os` (
  `Ordem De Serviço_idOrdem De Serviço` INT NOT NULL,
  `Peça_idPeça` INT NOT NULL,
  `idPeça` VARCHAR(45) NOT NULL,
  `quantidade` VARCHAR(45) NULL,
  `especialidade` VARCHAR(45) NULL,
  PRIMARY KEY (`Ordem De Serviço_idOrdem De Serviço`, `Peça_idPeça`, `idPeça`),
  INDEX `fk_Ordem De Serviço_has_Peça_Peça1_idx` (`Peça_idPeça` ASC) VISIBLE,
  INDEX `fk_Ordem De Serviço_has_Peça_Ordem De Serviço1_idx` (`Ordem De Serviço_idOrdem De Serviço` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem De Serviço_has_Peça_Ordem De Serviço1`
    FOREIGN KEY (`Ordem De Serviço_idOrdem De Serviço`)
    REFERENCES `mydb`.`Ordem De Serviço` (`idOrdem De Serviço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem De Serviço_has_Peça_Peça1`
    FOREIGN KEY (`Peça_idPeça`)
    REFERENCES `mydb`.`Peça` (`idPeça`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe_has_Ordem De Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipe_has_Ordem De Serviço` (
  `Equipe_idEquipe` INT NOT NULL,
  `Ordem De Serviço_idOrdem De Serviço` INT NOT NULL,
  PRIMARY KEY (`Equipe_idEquipe`, `Ordem De Serviço_idOrdem De Serviço`),
  INDEX `fk_Equipe_has_Ordem De Serviço_Ordem De Serviço1_idx` (`Ordem De Serviço_idOrdem De Serviço` ASC) VISIBLE,
  INDEX `fk_Equipe_has_Ordem De Serviço_Equipe1_idx` (`Equipe_idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Equipe_has_Ordem De Serviço_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `mydb`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipe_has_Ordem De Serviço_Ordem De Serviço1`
    FOREIGN KEY (`Ordem De Serviço_idOrdem De Serviço`)
    REFERENCES `mydb`.`Ordem De Serviço` (`idOrdem De Serviço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
